CREATE TABLE BOMTEST (
     ITEM_ID INTEGER NOT NULL, -- 품목식별자
     PARENT_ID INTEGER, -- 상위품목 식별자
     ITEM_NAME VARCHAR(20) NOT NULL, -- 품목이름
     ITEM_QTY INTEGER, -- 품목 개수
     PRIMARY KEY (ITEM_ID));

DELETE FROM BOMTEST;
SELECT * FROM BOMTEST;
    
INSERT INTO BOMTEST VALUES ( 1001, NULL, '컴퓨터', 1);
INSERT INTO BOMTEST VALUES ( 1002, 1001, '본체', 1);
INSERT INTO BOMTEST VALUES ( 1003, 1001, '모니터', 1);
INSERT INTO BOMTEST VALUES ( 1004, 1001, '프린터', 1);

INSERT INTO BOMTEST VALUES ( 1005, 1002, '메인보드', 1);
INSERT INTO BOMTEST VALUES ( 1006, 1002, '랜카드', 1);
INSERT INTO BOMTEST VALUES ( 1007, 1002, '파워서플라이', 1);
INSERT INTO BOMTEST VALUES ( 1008, 1005, 'CPU', 1);
INSERT INTO BOMTEST VALUES ( 1009, 1005, 'RAM', 1);
INSERT INTO BOMTEST VALUES ( 1010, 1005, '그래픽카드', 1);
INSERT INTO BOMTEST VALUES ( 1011, 1005, '기타장치', 1);

INSERT INTO BOMTEST VALUES ( 1005, 1003, '메인보드', 1);


SELECT BOM1.ITEM_NAME,
     BOM1.ITEM_ID,
     BOM2.ITEM_ID PAREMNT_ID,
     BOM2.ITEM_NAME PARENT_ITEM
FROM BOMTEST BOM1
LEFT JOIN BOMTEST BOM2 
	ON BOM1.PARENT_ID = BOM2.ITEM_ID
ORDER BY BOM1.ITEM_ID;





WITH RECURSIVE CTE AS (
	SELECT
		ITEM_ID,
		ITEM_NAME,
		PARENT_ID,
		1 AS LEVEL
	FROM BOMTEST
	WHERE
		PARENT_ID IS NULL
	UNION ALL
	SELECT
		P.ITEM_ID,
		P.ITEM_NAME,
		P.PARENT_ID,
		1 + LEVEL AS LEVEL
	FROM BOMTEST P
	INNER JOIN CTE ON P.PARENT_ID = CTE.ITEM_ID 
) 
SELECT
	ITEM_ID,
	IFNULL(PARENT_ID, 0) AS PARENT_ID,
	ITEM_NAME,
	LEVEL
FROM CTE ;